"""Updated Message model

Revision ID: a01bea414a7a
Revises: 9daa08d69792
Create Date: 2025-02-15 05:00:56.259530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a01bea414a7a'
down_revision = '9daa08d69792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'body',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('messages', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('messages', 'body',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
